source 'https://rubygems.org'
ruby '2.1.1'
#ruby-gemset=rails-4.0

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.5'

gem 'will_paginate'
gem 'bootstrap-will_paginate'

gem 'paper_trail', '~> 3.0.5'

# Use mysql as the database for Active Record
gem 'mysql2', '0.3.16'
#gem 'sqlite3'

# Use SCSS for stylesheets
gem 'bootstrap-sass', '3.2.0.1'
gem 'sass-rails', '4.0.2'
gem 'sprockets', '~> 2.11.0'
gem 'autoprefixer-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '2.1.1'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '4.0.1'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '3.0.4'
gem 'jquery-ui-rails', '5.0.0'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '1.1.1'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


gem 'devise', '3.2.4'
gem 'truncate_html', '0.9.2'

# For file uploading: https://github.com/carrierwaveuploader/carrierwave
gem 'carrierwave', '0.10.0'

# For admin console for the database models
gem 'activeadmin', github: 'gregbell/active_admin'


#CKEditor is a WYSIWYG editor
gem 'ckeditor', '4.1.0'

group :development, :test do
  # Adding rspec testing
  gem 'rspec-rails', '2.13.1'
  gem 'faker'
  gem 'populator'
end

group :test do
  # To make rspec more readable
  gem 'selenium-webdriver', '2.35.1'
  gem 'capybara', '2.1.0'
end